name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/playstore.png
    - assets/appstore.png

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/playstore.png"
  image_path_ios: "assets/appstore.png"