// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFwF6EaGaUq26_2g4nzUsUka9LNyNoJdg',
    appId: '1:150198810607:web:3cf5a619838360fa87681a',
    messagingSenderId: '150198810607',
    projectId: 'pokerpal-6e635',
    authDomain: 'pokerpal-6e635.firebaseapp.com',
    databaseURL: 'https://pokerpal-6e635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pokerpal-6e635.firebasestorage.app',
    measurementId: 'G-FTCS741Q0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-O3jgYatZiZEcwbokyihIQI7DIcCEeaA',
    appId: '1:150198810607:android:930df01d2543758f87681a',
    messagingSenderId: '150198810607',
    projectId: 'pokerpal-6e635',
    databaseURL: 'https://pokerpal-6e635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pokerpal-6e635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-UiHKGCaB9Sfyu7E2WM7EXwpQDtCof8A',
    appId: '1:150198810607:ios:0e54b5bdc1d6196f87681a',
    messagingSenderId: '150198810607',
    projectId: 'pokerpal-6e635',
    databaseURL: 'https://pokerpal-6e635-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pokerpal-6e635.firebasestorage.app',
    iosBundleId: 'com.example.pokerPal',
  );
}
